### ISSUE TITLE
About the test code

### ISSUE THREAD

**Issue by maoyali** [YinghaoHuang91/MuVS#10]
Thanks for sharing your code~
but when I only run 'gen_run_jobs_1.sh' with your test data, the result is very strange, it look like this:
/home/yck/桌面/2019-07-21 22-27-33屏幕截图.png
I did't change any code, who can tell me where the problem?

**Comment by YinghaoHuang91** [comment]
Hi thanks for your interest in our work and pointing this error out. I believe this issue is introduced in this extra line of code (Line 127 of smpl_batch.py, now already commented out) incorrectly added some time ago: 
![image](https://user-images.githubusercontent.com/13058193/61596347-61121d80-ac02-11e9-8b08-fee08f1d12b1.png)
Now the code should work again. Can you please give it a try? Thanks!

**Comment by maoyali** [comment]
ok, thanks~

**Comment by maoyali** [comment]
It works well !
